### ISSUE TITLE
殺人粒子特效沒有顯示

### ISSUE THREAD

**Issue by lulu2002** [lulu2002/Naluwan-Issues#4]
```
[12:09:04 ERROR]: [Server Thread] Could not pass event PlayerDeathEvent to ProjectileTrails v2.0.1
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.DIG_GLASS
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_282]
        at org.bukkit.Sound.valueOf(SourceFile:19) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at me.lulu.projectiletrails.nms.CommonNMS.getBlockBreakSound(CommonNMS.java:19) ~[?:?]
        at me.lulu.projectiletrails.trail.BlockBreakTrail.playMaterialBlockBreakSound(BlockBreakTrail.java:52) ~[?:?]
        at me.lulu.projectiletrails.trail.BlockBreakTrail.displayForKill(BlockBreakTrail.java:33) ~[?:?]
        at me.lulu.projectiletrails.listener.TrailListener.lambda$onDeath$0(TrailListener.java:56) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_282]
        at me.lulu.projectiletrails.listener.TrailListener.onDeath(TrailListener.java:56) ~[?:?]
        at spg.lgdev.events.executor.asm.generated.GeneratedEventExecutor47.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(SourceFile:76) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(SourceFile:62) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(SourceFile:70) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SourceFile:567) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SourceFile:554) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(SourceFile:394) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(SourceFile:471) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(SourceFile:903) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(SourceFile:828) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(SourceFile:596) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(SourceFile:1048) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(SourceFile:1202) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1449) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:45) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:15) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:26) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at spg.lgdev.thread.TickTask.run(SourceFile:26) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at spg.lgdev.thread.ThreadHandler.executeTask(SourceFile:103) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at spg.lgdev.thread.impl.ThreadHandlerReentrant.executeTask(SourceFile:35) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at spg.lgdev.thread.ThreadHandler.executeNext(SourceFile:75) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.executeNext(SourceFile:1595) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at spg.lgdev.thread.ThreadHandler.awaitTasks(SourceFile:86) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.sleepForTick(SourceFile:633) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:723) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at spg.lgdev.thread.ImanityThreads.lambda$buildServerThread$2(SourceFile:80) ~[ispigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by lulu2002** [comment]
已修正！
